{'data': {'formInfo': {'widgetMap': {
    '_S_URGENCY_DEGREE': {'codeId': '_S_URGENCY_DEGREE', 'extendFieldMap': {}, 'displaylinkageVos': [],
                          'options': [{'checked': "True", 'value': '普通', 'key': '1'},
                                      {'checked': "False", 'value': '紧急', 'key': '2'},
                                      {'checked': "False", 'value': '加急', 'key': '3'},
                                      {'checked': "False", 'value': '特急', 'key': '4'},
                                      {'checked': "False", 'value': '特提', 'key': '5'}], 'linkRule': [], 'title': '紧急程度',
                          'type': 'radioWidget', 'value': '1'},
    '_S_SERIAL': {'codeId': '_S_SERIAL', 'extendFieldMap': {}, 'title': '流水号', 'type': 'serialNumWidget',
                  'value': 'LSGYS-20210925-001'},
    '_S_DATE': {'codeId': '_S_DATE', 'fromNowOn': "False", 'title': '申请日期', 'type': 'dateWidget', 'value': 1632561121343},
    'Im_0': {'codeId': 'Im_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '图片', 'type': 'imageWidget', 'value': []},
    '_S_APPLY': {'eid': '19469603', 'codeId': '_S_APPLY', 'existEcosphere': "False", 'title': '提交人',
                 'type': 'personSelectWidget', 'personInfo': [
            {'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
             'companyName': '江苏谷登重型机械装备科技有限公司', 'jobTitle': 'ERP专员', 'name': '周为',
             'deptLongName': '江苏谷登重型机械装备科技有限公司/运营中心/信息化部', 'oid': '5f2e53bce4b0ce6aad23fa1e', 'dept': '信息化部',
             'userId': '5f2686c2e4b0aa487b634a9c'}], 'value': ['5f2e53bce4b0ce6aad23fa1e']},
    'Ta_0': {'codeId': 'Ta_0', 'extendFieldMap': {}, 'title': '说明', 'type': 'textAreaWidget', 'value': ''},
    'At_0': {'codeId': 'At_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '文件', 'type': 'attachmentWidget',
             'value': []},
    '_S_DEPT': {'eid': '19469603', 'codeId': '_S_DEPT', 'title': '所属部门', 'type': 'departmentSelectWidget', 'deptInfo': [
        {'name': '信息化部', 'orgId': '4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498', 'realLongName': '江苏谷登重型机械装备科技有限公司!运营中心!信息化部',
         'longName': '信息化部(运营中心)'}], 'selectCompanyOnly': "False", 'value': ['4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498']},
    '_S_TITLE': {'codeId': '_S_TITLE', 'extendFieldMap': {'titleEntity': {'kind': 'TITLE_DEFAULT', 'list': [
        {'formItem': '_S_APPLY', 'kind': 'ITEM_FORM_ITEM'}, {'formItem': '的', 'kind': 'ITEM_STRING'},
        {'formItem': '模板名称', 'kind': 'ITEM_TEMPLATENAME'}]}, 'defaultTitle': "True"}, 'title': '标题', 'type': 'textWidget',
                 'value': '周为的CG08 临时供应商评审(ERP)'}}, 'detailMap': {'Dd_0': {'buttonName': '添加明细', 'codeId': 'Dd_0',
                                                                           'widgetVos': {'Te_4': {'codeId': 'Te_4',
                                                                                                  'extendFieldMap': {
                                                                                                      'wordLimit': 200},
                                                                                                  'title': '新增说明',
                                                                                                  'type': 'textWidget'},
                                                                                         'Te_2': {'codeId': 'Te_2',
                                                                                                  'extendFieldMap': {
                                                                                                      'wordLimit': 200},
                                                                                                  'title': '地址',
                                                                                                  'type': 'textWidget'},
                                                                                         'Ra_2': {'codeId': 'Ra_2',
                                                                                                  'extendFieldMap': {},
                                                                                                  'displaylinkageVos': [],
                                                                                                  'options': [
                                                                                                      {'checked': "False",
                                                                                                       'value': '月结15天',
                                                                                                       'key': 'REewqJbs'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '月结30天',
                                                                                                       'key': '6fA4cby2'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '月结45天',
                                                                                                       'key': 'j3hh0nd0'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '月结60天',
                                                                                                       'key': 'XPLKfdoZ'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '月结90天',
                                                                                                       'key': 'XMHG4hYe'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '款到发货',
                                                                                                       'key': '4t7fOkRL'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '货到付款',
                                                                                                       'key': 'Bo0WFjQB'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '按比率付款',
                                                                                                       'key': 'sQNIGfx0'}],
                                                                                                  'linkRule': [],
                                                                                                  'title': '付款方式',
                                                                                                  'type': 'radioWidget'},
                                                                                         'Te_1': {'codeId': 'Te_1',
                                                                                                  'extendFieldMap': {
                                                                                                      'wordLimit': 200},
                                                                                                  'title': '代码',
                                                                                                  'type': 'textWidget'},
                                                                                         'Te_0': {'codeId': 'Te_0',
                                                                                                  'extendFieldMap': {
                                                                                                      'wordLimit': 200},
                                                                                                  'title': '供应商全称',
                                                                                                  'type': 'textWidget'},
                                                                                         'Ra_0': {'codeId': 'Ra_0',
                                                                                                  'extendFieldMap': {},
                                                                                                  'displaylinkageVos': [],
                                                                                                  'options': [
                                                                                                      {'checked': "False",
                                                                                                       'value': '原材料',
                                                                                                       'key': 'Vg9RytQm'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '动力源',
                                                                                                       'key': 'GLEP2S83'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '电器类',
                                                                                                       'key': 'p7vlqtAa'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '辅料类',
                                                                                                       'key': 'y2Tlqv7g'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '结构类',
                                                                                                       'key': 'cFC7W3Se'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '外协加工',
                                                                                                       'key': 'lFxoT8UO'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '设备类',
                                                                                                       'key': 'PPhDWB2J'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '液压类',
                                                                                                       'key': 'HE7i3pEF'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '钻具类',
                                                                                                       'key': 'RjUjCd1a'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '内部结算供应商',
                                                                                                       'key': 's9o5GVre'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '其他',
                                                                                                       'key': 'r3OkE258'}],
                                                                                                  'linkRule': [],
                                                                                                  'title': '组别',
                                                                                                  'type': 'radioWidget'},
                                                                                         'Ra_1': {'codeId': 'Ra_1',
                                                                                                  'extendFieldMap': {},
                                                                                                  'displaylinkageVos': [],
                                                                                                  'options': [
                                                                                                      {'checked': "False",
                                                                                                       'value': '13%增值税',
                                                                                                       'key': 'o2c7Z7z8'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '9%增值税',
                                                                                                       'key': '7e7ZHZhq'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '7%增值税',
                                                                                                       'key': 'DWSSFuMF'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '6%增值税',
                                                                                                       'key': 'NTGpzG3i'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '3%增值税',
                                                                                                       'key': 'cnrJK69B'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '1%增值税',
                                                                                                       'key': 'Z840bRxh'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '零税率的增值税',
                                                                                                       'key': 'P12Bqon0'}],
                                                                                                  'linkRule': [],
                                                                                                  'title': '税率',
                                                                                                  'type': 'radioWidget'},
                                                                                         'Nu_0': {'codeId': 'Nu_0',
                                                                                                  'decimalDigit': 0,
                                                                                                  'extendFieldMap': {},
                                                                                                  'detailCountName': '总数量',
                                                                                                  'title': '联系电话',
                                                                                                  'type': 'numberWidget',
                                                                                                  'detailCount': "False"},
                                                                                         'Cb_0': {'codeId': 'Cb_0',
                                                                                                  'extendFieldMap': {},
                                                                                                  'options': [
                                                                                                      {'checked': "False",
                                                                                                       'value': '采购',
                                                                                                       'key': 'AaBaCcDd'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '重型',
                                                                                                       'key': 'EeFfGgHh'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '制造',
                                                                                                       'key': 'IiJjKkLl'},
                                                                                                      {'checked': "False",
                                                                                                       'value': '装配',
                                                                                                       'key': 'MN7tcj1k'}],
                                                                                                  'title': '使用组织',
                                                                                                  'type': 'checkboxWidget'}},
                                                                           'extendFieldMap': {'showSerialNum': "False"},
                                                                           'widgetValue': [{'Te_4': '123', 'Te_2': '地址',
                                                                                            'Te_1': '代码',
                                                                                            'Ra_2': '6fA4cby2',
                                                                                            'Te_0': '名称',
                                                                                            'Ra_0': 'p7vlqtAa',
                                                                                            'Ra_1': 'DWSSFuMF',
                                                                                            '_id_': '1',
                                                                                            'Nu_0': '13337981899',
                                                                                            'Cb_0': ['AaBaCcDd',
                                                                                                     'EeFfGgHh',
                                                                                                     'IiJjKkLl',
                                                                                                     'MN7tcj1k']}],
                                                                           'imageInfo': {}, 'title': '供应商信息',
                                                                           'type': 'detailedWidget'}}},
          'basicInfo': {'nodeName': '完成审批', 'eid': '19469603', 'eventId': 'd8b0347a-adb9-40c0-b934-d6499760b759',
                        'formDefId': '614ee6c797baa6000174f60e', 'dataType': 1,
                        'myNetworkInfo': {'eid': '19469603', 'name': '江苏谷登重型机械装备科技有限公司'}, 'nodeType': 'END',
                        'title': 'CG08 临时供应商评审(ERP)', 'flowInstId': '614ee7e1a9ffc90001dd50fa',
                        'formCodeId': 'a65db625bc2945a39fbd681f69159f4d', 'actionType': 'reach', 'myPersonInfo': {
                  'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
                  'jobNo': '20080103', 'name': '周为', 'oid': '5f2e53bce4b0ce6aad23fa1e'},
                        'formInstId': '614ee7e1a27409000168d4b0', 'eventTime': 1632561121872,
                        'myDeptInfo': {'name': '信息化部', 'orgId': '4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498'},
                        'interfaceId': 'OIhQmuoe', 'interfaceName': '新增供应商', 'returned': "False",
                        'nodeId': '614ee7e1a9ffc90001dd5114'}}, 'success': "True", 'errorCode': 0}
