{'data': {'formInfo': {'widgetMap': {
    '_S_URGENCY_DEGREE': {'codeId': '_S_URGENCY_DEGREE', 'extendFieldMap': {}, 'displaylinkageVos': [],
                          'options': [{'checked': "True", 'value': '普通', 'key': '1'},
                                      {'checked': "False", 'value': '紧急', 'key': '2'},
                                      {'checked': "False", 'value': '加急', 'key': '3'},
                                      {'checked': "False", 'value': '特急', 'key': '4'},
                                      {'checked': "False", 'value': '特提', 'key': '5'}], 'linkRule': [], 'title': '紧急程度',
                          'type': 'radioWidget', 'value': '1'},
    '_S_SERIAL': {'codeId': '_S_SERIAL', 'extendFieldMap': {}, 'title': '流水号', 'type': 'serialNumWidget',
                  'value': 'ZSGYS-20210926-003'},
    '_S_DATE': {'codeId': '_S_DATE', 'fromNowOn': "False", 'title': '申请日期', 'type': 'dateWidget', 'value': 1632648630973},
    'Im_0': {'codeId': 'Im_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '图片', 'type': 'imageWidget', 'value': []},
    'Ta_0': {'codeId': 'Ta_0', 'extendFieldMap': {}, 'title': '说明', 'type': 'textAreaWidget', 'value': ''},
    '_S_APPLY': {'eid': '19469603', 'codeId': '_S_APPLY', 'existEcosphere': "False", 'title': '提交人',
                 'type': 'personSelectWidget', 'personInfo': [
            {'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
             'companyName': '江苏谷登重型机械装备科技有限公司', 'jobTitle': 'ERP专员', 'name': '周为',
             'deptLongName': '江苏谷登重型机械装备科技有限公司/运营中心/信息化部', 'oid': '5f2e53bce4b0ce6aad23fa1e', 'dept': '信息化部',
             'userId': '5f2686c2e4b0aa487b634a9c'}], 'value': ['5f2e53bce4b0ce6aad23fa1e']},
    'At_0': {'codeId': 'At_0', 'extendFieldMap': {}, 'maximum': 200, 'title': '文件', 'type': 'attachmentWidget',
             'value': []},
    '_S_DEPT': {'eid': '19469603', 'codeId': '_S_DEPT', 'title': '所属部门', 'type': 'departmentSelectWidget', 'deptInfo': [
        {'name': '信息化部', 'orgId': '4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498', 'realLongName': '江苏谷登重型机械装备科技有限公司!运营中心!信息化部',
         'longName': '信息化部(运营中心)'}], 'selectCompanyOnly': "False", 'value': ['4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498']},
    '_S_TITLE': {'codeId': '_S_TITLE', 'extendFieldMap': {'titleEntity': {'kind': 'TITLE_DEFAULT', 'list': [
        {'formItem': '_S_APPLY', 'kind': 'ITEM_FORM_ITEM'}, {'formItem': '的', 'kind': 'ITEM_STRING'},
        {'formItem': '模板名称', 'kind': 'ITEM_TEMPLATENAME'}]}, 'defaultTitle': "True"}, 'title': '标题', 'type': 'textWidget',
                 'value': '周为的CG09 临时供应商转正申请(ERP)'}}, 'detailMap': {'Dd_0': {'buttonName': '添加明细', 'codeId': 'Dd_0',
                                                                             'widgetVos': {'Te_1': {'codeId': 'Te_1',
                                                                                                    'extendFieldMap': {
                                                                                                        'wordLimit': 200},
                                                                                                    'title': '供应商代码',
                                                                                                    'type': 'textWidget'},
                                                                                           'Te_0': {'codeId': 'Te_0',
                                                                                                    'extendFieldMap': {
                                                                                                        'wordLimit': 200},
                                                                                                    'title': '供应商全称',
                                                                                                    'type': 'textWidget'}},
                                                                             'extendFieldMap': {'showSerialNum': "False"},
                                                                             'widgetValue': [
                                                                                 {'Te_1': '代码', 'Te_0': '名称',
                                                                                  '_id_': '1'}], 'imageInfo': {},
                                                                             'title': '转正供应商清单',
                                                                             'type': 'detailedWidget'}}},
          'basicInfo': {'nodeName': '完成审批', 'eid': '19469603', 'eventId': '360401cd-f45c-418a-9146-acbb667a565e',
                        'formDefId': '61503d758c89850001a5e909', 'dataType': 1,
                        'myNetworkInfo': {'eid': '19469603', 'name': '江苏谷登重型机械装备科技有限公司'}, 'nodeType': 'END',
                        'title': 'CG09 临时供应商转正申请(ERP)', 'flowInstId': '61503db784aa540001cf0f54',
                        'formCodeId': 'ad9707aabe6042499b1ac5cab259d515', 'actionType': 'reach', 'myPersonInfo': {
                  'image': 'https://static.yunzhijia.com/space/c/photo/load?id=60d59879fc15d6000143ffae',
                  'jobNo': '20080103', 'name': '周为', 'oid': '5f2e53bce4b0ce6aad23fa1e'},
                        'formInstId': '61503db77c6e270001dd15b4', 'eventTime': 1632648631792,
                        'myDeptInfo': {'name': '信息化部', 'orgId': '4eebc4b6-0c4e-11ec-8a77-ecf4bbea1498'},
                        'interfaceId': 'RG7HaloM', 'interfaceName': '更新', 'returned': "False",
                        'nodeId': '61503db784aa540001cf0fa4'}}, 'success': "True", 'errorCode': 0}
